takeimages: rs-save-to-disk.cpp
	g++ -std=c++11 rs-save-to-disk.cpp -o takeimages -lrealsense2 -lwiringPi -lwiringPiDev

debug: rs-save-to-disk.cpp
	g++ -std=c++11 rs-save-to-disk.cpp -g -o takeimages -lrealsense2 -lwiringPi -lwiringPiDev

nopi: rs-save-to-disk.cpp
	g++ -std=c++11 rs-save-to-disk.cpp -g -o takeimages -lrealsense2
